In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('data\cleaned_dataset.csv')
df.head()

   Gesture        Ax        Ay        Az        Gx        Gy        Gz
0        0  0.327250  0.972020  0.978133  0.972500  0.282577  0.551446
1        0  0.323264  0.978824  0.978574  0.968821  0.297214  0.549468
2        0  0.331779  0.970411  0.978970  0.970301  0.260290  0.551673
3        0  0.313128  0.981825  0.978850  0.968926  0.284897  0.547513
4        0  0.222645  0.968425  0.979011  0.969466  0.267591  0.550981

In [3]:
X = df[['Ax', 'Ay', 'Az', 'Gx', 'Gy', 'Gz']]
y = df['Gesture']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.15, random_state=42)

In [5]:
y_train.head()

93     0
69     0
203    1
171    1
152    1
Name: Gesture, dtype: int64

In [6]:
X_train.head()

           Ax        Ay        Az        Gx        Gy        Gz
93   0.373526  0.959517  0.978514  0.968943  0.273717  0.549192
69   0.294803  0.949733  0.945690  0.967886  0.267014  0.549612
203  0.335536  0.854595  0.978258  0.967506  0.278506  0.553692
171  0.291664  0.899851  0.977883  0.967934  0.279439  0.550018
152  0.255149  0.891572  0.978456  0.967804  0.249687  0.555387

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.callbacks import EarlyStopping, LearningRateScheduler

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
model = Sequential([
    Input(shape=(X_train.shape[1],)),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy',
              metrics=['accuracy'])

early_stopping = EarlyStopping(
    monitor='val_loss', patience=5, restore_best_weights=True)
lr_schedual = LearningRateScheduler(lambda epoch: 1e-3 * 0.9 ** epoch)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [13]:
history = model.fit(X_train, y_train, epochs=200, batch_size=32, validation_data=(
    X_test, y_test), callbacks=(early_stopping, lr_schedual))

Epoch 1/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - accuracy: 0.5028 - loss: 0.7981 - val_accuracy: 0.6364 - val_loss: 0.7124 - learning_rate: 0.0010
Epoch 2/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6354 - loss: 0.6626 - val_accuracy: 0.7879 - val_loss: 0.6937 - learning_rate: 9.0000e-04
Epoch 3/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6354 - loss: 0.7280 - val_accuracy: 0.7576 - val_loss: 0.6752 - learning_rate: 8.1000e-04
Epoch 4/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6796 - loss: 0.6417 - val_accuracy: 0.7879 - val_loss: 0.6654 - learning_rate: 7.2900e-04
Epoch 5/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6409 - loss: 0.6128 - val_accuracy: 0.8182 - val_loss: 0.6558 - learning_rate: 6.5610e-04
Epoch 6/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6851 - loss: 0.6584 - val_accuracy: 0.8182 - val_loss: 0.6498 - learning_rate: 5.9049e-04
Epoch 7/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6851 - loss: 0.5628 - val_accuracy: 0.8182 - val_loss: 0.6467 - learning_rate: 5.3144e-04
Epoch 8/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6740 - loss: 0.6676 - val_accuracy: 0.8182 - val_loss: 0.6432 - learning_rate: 4.7830e-04
Epoch 9/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.5397 - val_accuracy: 0.8182 - val_loss: 0.6383 - learning_rate: 4.3047e-04
Epoch 10/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6796 - loss: 0.6146 - val_accuracy: 0.8485 - val_loss: 0.6329 - learning_rate: 3.8742e-04
Epoch 11/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6906 - loss: 0.6131 - val_accuracy: 0.8485 - val_loss: 0.6271 - learning_rate: 3.4868e-04
Epoch 12/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7403 - loss: 0.6184 - val_accuracy: 0.8485 - val_loss: 0.6216 - learning_rate: 3.1381e-04
Epoch 13/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6906 - loss: 0.6288 - val_accuracy: 0.8485 - val_loss: 0.6174 - learning_rate: 2.8243e-04
Epoch 14/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7845 - loss: 0.5613 - val_accuracy: 0.8485 - val_loss: 0.6144 - learning_rate: 2.5419e-04
Epoch 15/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7569 - loss: 0.5997 - val_accuracy: 0.8485 - val_loss: 0.6113 - learning_rate: 2.2877e-04
Epoch 16/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.5809 - val_accuracy: 0.8485 - val_loss: 0.6085 - learning_rate: 2.0589e-04
Epoch 17/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7072 - loss: 0.5691 - val_accuracy: 0.8485 - val_loss: 0.6055 - learning_rate: 1.8530e-04
Epoch 18/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5535 - val_accuracy: 0.8485 - val_loss: 0.6021 - learning_rate: 1.6677e-04
Epoch 19/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7403 - loss: 0.5703 - val_accuracy: 0.8485 - val_loss: 0.5983 - learning_rate: 1.5009e-04
Epoch 20/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7790 - loss: 0.5170 - val_accuracy: 0.8485 - val_loss: 0.5948 - learning_rate: 1.3509e-04
Epoch 21/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.5900 - val_accuracy: 0.8485 - val_loss: 0.5913 - learning_rate: 1.2158e-04
Epoch 22/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.5274 - val_accuracy: 0.8485 - val_loss: 0.5880 - learning_rate: 1.0942e-04
Epoch 23/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7182 - loss: 0.5828 - val_accuracy: 0.8485 - val_loss: 0.5852 - learning_rate: 9.8477e-05
Epoch 24/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7569 - loss: 0.5977 - val_accuracy: 0.8485 - val_loss: 0.5824 - learning_rate: 8.8629e-05
Epoch 25/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7293 - loss: 0.5924 - val_accuracy: 0.8485 - val_loss: 0.5800 - learning_rate: 7.9766e-05
Epoch 26/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7901 - loss: 0.5034 - val_accuracy: 0.8485 - val_loss: 0.5773 - learning_rate: 7.1790e-05
Epoch 27/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7182 - loss: 0.5372 - val_accuracy: 0.8485 - val_loss: 0.5746 - learning_rate: 6.4611e-05
Epoch 28/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7348 - loss: 0.5644 - val_accuracy: 0.8485 - val_loss: 0.5719 - learning_rate: 5.8150e-05
Epoch 29/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7790 - loss: 0.5217 - val_accuracy: 0.8485 - val_loss: 0.5686 - learning_rate: 5.2335e-05
Epoch 30/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5644 - val_accuracy: 0.8485 - val_loss: 0.5655 - learning_rate: 4.7101e-05
Epoch 31/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7017 - loss: 0.6136 - val_accuracy: 0.8485 - val_loss: 0.5625 - learning_rate: 4.2391e-05
Epoch 32/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.5459 - val_accuracy: 0.8485 - val_loss: 0.5597 - learning_rate: 3.8152e-05
Epoch 33/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.5815 - val_accuracy: 0.8485 - val_loss: 0.5569 - learning_rate: 3.4337e-05
Epoch 34/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.5572 - val_accuracy: 0.8485 - val_loss: 0.5538 - learning_rate: 3.0903e-05
Epoch 35/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6961 - loss: 0.5642 - val_accuracy: 0.8485 - val_loss: 0.5504 - learning_rate: 2.7813e-05
Epoch 36/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7127 - loss: 0.5593 - val_accuracy: 0.8485 - val_loss: 0.5477 - learning_rate: 2.5032e-05
Epoch 37/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5932 - val_accuracy: 0.8485 - val_loss: 0.5453 - learning_rate: 2.2528e-05
Epoch 38/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5310 - val_accuracy: 0.8485 - val_loss: 0.5426 - learning_rate: 2.0276e-05
Epoch 39/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7459 - loss: 0.5348 - val_accuracy: 0.8485 - val_loss: 0.5400 - learning_rate: 1.8248e-05
Epoch 40/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5436 - val_accuracy: 0.8485 - val_loss: 0.5373 - learning_rate: 1.6423e-05
Epoch 41/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7293 - loss: 0.6051 - val_accuracy: 0.8485 - val_loss: 0.5350 - learning_rate: 1.4781e-05
Epoch 42/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7182 - loss: 0.5753 - val_accuracy: 0.8485 - val_loss: 0.5322 - learning_rate: 1.3303e-05
Epoch 43/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7514 - loss: 0.5961 - val_accuracy: 0.8485 - val_loss: 0.5292 - learning_rate: 1.1973e-05
Epoch 44/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7680 - loss: 0.5144 - val_accuracy: 0.8485 - val_loss: 0.5271 - learning_rate: 1.0775e-05
Epoch 45/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7624 - loss: 0.5158 - val_accuracy: 0.8485 - val_loss: 0.5251 - learning_rate: 9.6977e-06
Epoch 46/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5378 - val_accuracy: 0.8485 - val_loss: 0.5221 - learning_rate: 8.7280e-06
Epoch 47/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7735 - loss: 0.5265 - val_accuracy: 0.8485 - val_loss: 0.5201 - learning_rate: 7.8552e-06
Epoch 48/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7238 - loss: 0.5250 - val_accuracy: 0.8485 - val_loss: 0.5171 - learning_rate: 7.0697e-06
Epoch 49/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.6436 - val_accuracy: 0.8485 - val_loss: 0.5144 - learning_rate: 6.3627e-06
Epoch 50/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.5332 - val_accuracy: 0.8485 - val_loss: 0.5119 - learning_rate: 5.7264e-06
Epoch 51/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.5581 - val_accuracy: 0.8485 - val_loss: 0.5095 - learning_rate: 5.1538e-06
Epoch 52/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.5746 - val_accuracy: 0.8485 - val_loss: 0.5074 - learning_rate: 4.6384e-06
Epoch 53/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5251 - val_accuracy: 0.8485 - val_loss: 0.5053 - learning_rate: 4.1746e-06
Epoch 54/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.5306 - val_accuracy: 0.8485 - val_loss: 0.5035 - learning_rate: 3.7571e-06
Epoch 55/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7238 - loss: 0.5683 - val_accuracy: 0.8485 - val_loss: 0.5015 - learning_rate: 3.3814e-06
Epoch 56/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5500 - val_accuracy: 0.8485 - val_loss: 0.4992 - learning_rate: 3.0433e-06
Epoch 57/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7680 - loss: 0.5431 - val_accuracy: 0.8485 - val_loss: 0.4972 - learning_rate: 2.7389e-06
Epoch 58/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7459 - loss: 0.5596 - val_accuracy: 0.8485 - val_loss: 0.4950 - learning_rate: 2.4650e-06
Epoch 59/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7127 - loss: 0.5453 - val_accuracy: 0.8485 - val_loss: 0.4935 - learning_rate: 2.2185e-06
Epoch 60/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7238 - loss: 0.5540 - val_accuracy: 0.8485 - val_loss: 0.4924 - learning_rate: 1.9967e-06
Epoch 61/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7459 - loss: 0.5455 - val_accuracy: 0.8485 - val_loss: 0.4914 - learning_rate: 1.7970e-06
Epoch 62/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7680 - loss: 0.5493 - val_accuracy: 0.8485 - val_loss: 0.4892 - learning_rate: 1.6173e-06
Epoch 63/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7127 - loss: 0.5551 - val_accuracy: 0.8485 - val_loss: 0.4884 - learning_rate: 1.4556e-06
Epoch 64/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7624 - loss: 0.5231 - val_accuracy: 0.8485 - val_loss: 0.4869 - learning_rate: 1.3100e-06
Epoch 65/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7569 - loss: 0.5404 - val_accuracy: 0.8485 - val_loss: 0.4852 - learning_rate: 1.1790e-06
Epoch 66/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.5406 - val_accuracy: 0.8485 - val_loss: 0.4834 - learning_rate: 1.0611e-06
Epoch 67/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7182 - loss: 0.5427 - val_accuracy: 0.8485 - val_loss: 0.4816 - learning_rate: 9.5500e-07
Epoch 68/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7017 - loss: 0.5812 - val_accuracy: 0.8485 - val_loss: 0.4807 - learning_rate: 8.5950e-07
Epoch 69/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7624 - loss: 0.5864 - val_accuracy: 0.8182 - val_loss: 0.4796 - learning_rate: 7.7355e-07
Epoch 70/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7790 - loss: 0.5327 - val_accuracy: 0.8182 - val_loss: 0.4787 - learning_rate: 6.9620e-07
Epoch 71/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7514 - loss: 0.5705 - val_accuracy: 0.8182 - val_loss: 0.4775 - learning_rate: 6.2658e-07
Epoch 72/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7293 - loss: 0.5594 - val_accuracy: 0.8182 - val_loss: 0.4773 - learning_rate: 5.6392e-07
Epoch 73/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7514 - loss: 0.5715 - val_accuracy: 0.8182 - val_loss: 0.4762 - learning_rate: 5.0753e-07
Epoch 74/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7514 - loss: 0.5541 - val_accuracy: 0.8182 - val_loss: 0.4753 - learning_rate: 4.5678e-07
Epoch 75/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7901 - loss: 0.5210 - val_accuracy: 0.8182 - val_loss: 0.4743 - learning_rate: 4.1110e-07
Epoch 76/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5843 - val_accuracy: 0.8182 - val_loss: 0.4733 - learning_rate: 3.6999e-07
Epoch 77/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7569 - loss: 0.5129 - val_accuracy: 0.8182 - val_loss: 0.4732 - learning_rate: 3.3299e-07
Epoch 78/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7127 - loss: 0.5809 - val_accuracy: 0.8182 - val_loss: 0.4727 - learning_rate: 2.9969e-07
Epoch 79/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7182 - loss: 0.5454 - val_accuracy: 0.8182 - val_loss: 0.4710 - learning_rate: 2.6972e-07
Epoch 80/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7072 - loss: 0.5800 - val_accuracy: 0.8182 - val_loss: 0.4700 - learning_rate: 2.4275e-07
Epoch 81/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7569 - loss: 0.5442 - val_accuracy: 0.8182 - val_loss: 0.4690 - learning_rate: 2.1847e-07
Epoch 82/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7459 - loss: 0.5466 - val_accuracy: 0.8182 - val_loss: 0.4680 - learning_rate: 1.9663e-07
Epoch 83/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7182 - loss: 0.5763 - val_accuracy: 0.8182 - val_loss: 0.4681 - learning_rate: 1.7696e-07
Epoch 84/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6961 - loss: 0.5613 - val_accuracy: 0.8182 - val_loss: 0.4688 - learning_rate: 1.5927e-07
Epoch 85/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7403 - loss: 0.5881 - val_accuracy: 0.8182 - val_loss: 0.4679 - learning_rate: 1.4334e-07
Epoch 86/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7238 - loss: 0.6451 - val_accuracy: 0.8182 - val_loss: 0.4665 - learning_rate: 1.2901e-07
Epoch 87/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.5214 - val_accuracy: 0.8182 - val_loss: 0.4649 - learning_rate: 1.1611e-07
Epoch 88/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7680 - loss: 0.5347 - val_accuracy: 0.8182 - val_loss: 0.4639 - learning_rate: 1.0450e-07
Epoch 89/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7956 - loss: 0.5507 - val_accuracy: 0.8182 - val_loss: 0.4625 - learning_rate: 9.4046e-08
Epoch 90/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7293 - loss: 0.5725 - val_accuracy: 0.8182 - val_loss: 0.4624 - learning_rate: 8.4641e-08
Epoch 91/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7459 - loss: 0.5555 - val_accuracy: 0.8182 - val_loss: 0.4612 - learning_rate: 7.6177e-08
Epoch 92/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7845 - loss: 0.5264 - val_accuracy: 0.8182 - val_loss: 0.4605 - learning_rate: 6.8560e-08
Epoch 93/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.5140 - val_accuracy: 0.8182 - val_loss: 0.4596 - learning_rate: 6.1704e-08
Epoch 94/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7735 - loss: 0.5511 - val_accuracy: 0.8182 - val_loss: 0.4590 - learning_rate: 5.5533e-08
Epoch 95/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7569 - loss: 0.5459 - val_accuracy: 0.8182 - val_loss: 0.4585 - learning_rate: 4.9980e-08
Epoch 96/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7403 - loss: 0.5734 - val_accuracy: 0.8182 - val_loss: 0.4580 - learning_rate: 4.4982e-08
Epoch 97/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7348 - loss: 0.5583 - val_accuracy: 0.8182 - val_loss: 0.4571 - learning_rate: 4.0484e-08
Epoch 98/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7403 - loss: 0.5467 - val_accuracy: 0.8182 - val_loss: 0.4563 - learning_rate: 3.6435e-08
Epoch 99/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7459 - loss: 0.5531 - val_accuracy: 0.8182 - val_loss: 0.4561 - learning_rate: 3.2792e-08
Epoch 100/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7624 - loss: 0.5468 - val_accuracy: 0.8182 - val_loss: 0.4562 - learning_rate: 2.9513e-08
Epoch 101/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7182 - loss: 0.5804 - val_accuracy: 0.8182 - val_loss: 0.4557 - learning_rate: 2.6561e-08
Epoch 102/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7845 - loss: 0.5369 - val_accuracy: 0.8182 - val_loss: 0.4557 - learning_rate: 2.3905e-08
Epoch 103/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7569 - loss: 0.5321 - val_accuracy: 0.8182 - val_loss: 0.4558 - learning_rate: 2.1515e-08
Epoch 104/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7569 - loss: 0.5667 - val_accuracy: 0.8182 - val_loss: 0.4555 - learning_rate: 1.9363e-08
Epoch 105/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7514 - loss: 0.5529 - val_accuracy: 0.8182 - val_loss: 0.4555 - learning_rate: 1.7427e-08
Epoch 106/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7624 - loss: 0.5153 - val_accuracy: 0.8182 - val_loss: 0.4549 - learning_rate: 1.5684e-08
Epoch 107/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7348 - loss: 0.6021 - val_accuracy: 0.8182 - val_loss: 0.4546 - learning_rate: 1.4116e-08
Epoch 108/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7569 - loss: 0.5288 - val_accuracy: 0.8182 - val_loss: 0.4543 - learning_rate: 1.2704e-08
Epoch 109/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7569 - loss: 0.5824 - val_accuracy: 0.8182 - val_loss: 0.4555 - learning_rate: 1.1434e-08
Epoch 110/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7569 - loss: 0.5329 - val_accuracy: 0.8182 - val_loss: 0.4564 - learning_rate: 1.0290e-08
Epoch 111/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7569 - loss: 0.5018 - val_accuracy: 0.8182 - val_loss: 0.4565 - learning_rate: 9.2614e-09
Epoch 112/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7514 - loss: 0.5747 - val_accuracy: 0.8182 - val_loss: 0.4558 - learning_rate: 8.3352e-09
Epoch 113/200
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7293 - loss: 0.5676 - val_accuracy: 0.8182 - val_loss: 0.4553 - learning_rate: 7.5017e-09

In [14]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'test_loss: {test_loss}, test_accuracy: {test_accuracy}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8182 - loss: 0.4543
test_loss: 0.454288512468338, test_accuracy: 0.8181818127632141

In [15]:
y_hat = model.predict(X_test)
y_hat = [0 if val < 0.5 else 1 for val in y_hat]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step

In [19]:
print(y_train.value_counts())

Gesture
0    91
1    90
Name: count, dtype: int64

In [20]:
accuracy_score(y_test, y_hat)

0.8181818181818182

In [21]:
model.save('tfModel.keras')

In [22]:
del model

In [23]:
model = load_model('tfModel.keras')

In [24]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'test_loss: {test_loss:.4f}')
print(f'test_accuracy: {test_accuracy * 100:.2f}%')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8182 - loss: 0.4543
test_loss: 0.4543
test_accuracy: 81.82%